### ISSUE TITLE
Enable desugaring if needed

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.colorfilters#187]
Disabled for now, because it's only needed for lower API levels.
And Android-JUnit5 has a 26 lower bound.

```toml
desugar = "2.0.3"
android-desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
```

```gradle.kts
//<editor-fold desc="Desugaring">
// Desugaring setup so that we can use Java 8/11 features on lower APIs.
// e.g. to support Mockito 5.x on API 23 and lower.
plugins.withId("com.android.base") {
	android {
		compileOptions {
			isCoreLibraryDesugaringEnabled = true
		}
		dependencies {
			add("coreLibraryDesugaring", libs.android.desugar)
		}
		(this@android as? AppExtension)?.apply {
			defaultConfig.multiDexEnabled = true
		}
	}
}
//</editor-fold>
```
